---
site_name: Documentación AVAST
docs_dir: docs
theme:
  name: readthedocs

nav:
  - Inicio: index.md
  - Matriculación en talleres: asignacion.md
  - Detalles técnicos matriculación: asignacion-tecnico.md
